#!/bin/sh
# vim: set ts=4:
#
# Ensure that ruby, bundler and all gem dependencies are installed.
#
set -eu

cd "$(dirname "$0")/.."
. script/utils.sh

export GEM_HOME="$(pwd)/.gem"
export PATH="$GEM_HOME/bin:$PATH"
rehash 2>/dev/null || true

if ! has ruby || ! has gem; then
	die 'Ruby not found!' \
		'TIP: Install package "ruby" using system package manager'
fi

if ! has bundler; then
	einfo 'Bundler not found, installing...'
	gem install bundler
fi

if ! bundle check >/dev/null 2>&1; then
	if ! (cd .gem; ruby -e 'require "mkmf"; exit MakeMakefile.have_devel?'); then
		die 'Ruby header files or C/C++ toolchain not installed' \
			'TIP: Try to install package ruby-dev or ruby-devel using system package manager'
	fi

	einfo 'Installing gem dependencies...'
	bundle install
fi
