#!/bin/sh
# vim: set ts=4:
#
# Ensure that ruby, bundler and all gem dependencies are installed.
#
set -eu

# Minimal required Ruby version
RUBY_MIN_VERSION='2.2.2'


cd "$(dirname "$0")/.."
. script/utils.sh

export GEM_HOME="$(pwd)/.gem"
export PATH="$GEM_HOME/bin:$PATH"
rehash 2>/dev/null || true

if ! has ruby || ! has gem; then
	die 'Ruby not found!' \
		'TIP: Install package "ruby" using system package manager'
fi

ruby_ver="$(ruby -e 'puts RUBY_VERSION')"
if [ $(compver "$ruby_ver" "$RUBY_MIN_VERSION") = -1 ]; then
	die "Ruby $RUBY_MIN_VERSION or later is required, but you have $ruby_ver!" \
		'TIP: Update package "ruby" or install newer version with rbenv'
fi

if ! has bundler; then
	einfo 'Bundler not found, installing...'
	gem install bundler --no-document
fi

if [ "${BUILD_ENV:-}" = 'production' ]; then
	export BUNDLE_WITHOUT='development'
fi
# Workaround for https://github.com/bundler/bundler/issues/3288
sed -i.orig '/BUNDLE_WITHOUT/d' .bundle/config 2>/dev/null || true

if ! bundle check >/dev/null 2>&1; then
	if ! (cd .gem; ruby -e 'require "mkmf"; exit MakeMakefile.have_devel? ? 0 : 1'); then
		die 'Ruby header files or C/C++ toolchain not installed' \
			'TIP: Try to install package ruby-dev or ruby-devel using system package manager'
	fi

	einfo 'Installing gem dependencies...'
	bundle install
fi
