#!/bin/sh
# vim: set ts=4:
#
# Build the site in the specified build directory.
#
set -eu

: ${BUILD_DIR:="build"}
: ${BUILD_ENV:="production"}


cd "$(dirname "$0")/.."
. script/bootstrap

einfo 'Building site...'
MM_ENV=$BUILD_ENV bundle exec \
	middleman build --build-dir="$BUILD_DIR" --watcher-disable
