#!/bin/sh
# vim: set ts=4:
#
# Run development HTTP server, watch the source files and automatically
# reload the browser whenever files change.
#
set -eu

: ${BUILD_ENV:="development"}


cd "$(dirname "$0")/.."
. script/bootstrap

MM_ENV=$BUILD_ENV bundle exec \
	middleman server
