= MQTT – Message transfer protocol

== MQTT Basics

- Simple, Lightweight and open message protocol.
- Each message consists of *topic* and *payload*.
- Topic is describing the meaning of the data in payload.
  Topic uses tree-like structure with `/` symbol.
  Example topics: `bedroom/temperature`, `kitchen/light/set`.
- MQTT server is called *Broker* and clients can *publish* messages and *subscribe* to different types of topics.
- In subscribe topics the wildcard `+` can be used for single level subscription and symbol `&num;` for multi level subscription.
  Symbol `&num;` can be used only at the end of subscribed topic.
  http://www.hivemq.com/blog/mqtt-essentials-part-5-mqtt-topics-best-practices[More on topics]


== Mosquitto MQTT broker

BigClown uses open-source https://mosquitto.org/[Mosquitto] broker which is running inside Docker.

To test MQTT and see the sent messages you can subscribe to topic with:

[source]
docker exec hub mosquitto_sub -v -t 'nodes/bridge/0/#'

If you would like to connect from outside of the docker or from different machine, you can remove the `docker exec hub` and add `-h <ip/host>` parameter of the address of running broker.

To publish a message use *mosquitto_pub* command:

[source]
docker exec hub mosquitto_pub -t nodes/bridge/0/relay/i2c0-3b/set -m '{"state": true}'


== Mosquitto configuration

You can edit Mosquitto settings in the configuration file which is located in `/etc/mosquitto/mosquitto.conf` inside the Docker.


=== MQTT Bridge

Bridging two MQTT servers together is useful for example when you have your local MQTT server behind NAT and you would like to publish messages from the outside/Internet.
You have to create public MQTT server (for example on AWS server) which you bridge with your home MQTT server.
In this use case your local server will connect to your public server in AWS.
So you have to configure your local server with commands below.

[source]
----
# Bridge to AWS
connection aws
address your.server.com

# Optional password, you should also use TLS to protect credentials
remote_username root
remote_password root

#topic <topic> [[[out | in | both] qos-level] local-prefix remote-prefix]
topic # in 0 /home/# /home_remote/#
----

Topic command will subscribe to all topics (`topic &num;`) on remote server under `/home_remote/&num;` and will publish them on local server under `/home/#`.
Parameter `in` describes direction and zero `0` means no QoS.

=== Graphical tool mqtt-spy

For diagnostic purposes, you can also use the tool with a graphical interface http://kamilfb.github.io/mqtt-spy/[mqtt-spy]
https://github.com/eclipse/paho.mqtt-spy/wiki

Then connect to your broker IP address and subscribe to the topic.
